### ISSUE TITLE
Standalone app

### ISSUE THREAD

**Issue by QuentinDela** [domagojk/serverless-console#14]
Hey, 

Have you ever thought about building a standalone mac app a bit like https://dynobase.dev ?
It might bring the opportunity for a better experience, I would definitely purchase it.

Thanks,

**Comment by domagojk** [comment]
Hey, yes I did, and even started doing that, but it is not a small task, as you might imagine.
Also, I started working on DynamoDB console for this extension and I think integrating it with vs code makes it better than I could do it myself (since it uses editor, vscode dialogs, themes etc).

I was also planning on releasing Dynamodb console as a "pro" feature, for which you would need a license.

What do you think are benefits in going on a standalone app?

**Comment by QuentinDela** [comment]
Hey,

Actually, I am not proficient enough to see what are VS Code limitations.
It feels like for now you are making it working great actually.

TBH, I don't know how to answer your question.

I really believe in the opportunity to build a professional tool serverless tool and I wish this project to become more than a VS Code extension, even if for now VSCode seems to be the best MVP option.
I am happy to see that paying features are coming :)

Also, one obvious benefit would be to open the tool to people not using VS Code.

Thanks a lot for the extension, it's working great.

**Comment by domagojk** [comment]
Sure, thanks for the support! :)

My idea is to build a serverless tool, so DynamoDB is next, then I was thinking SQS, but will first see how well DynamoDB/license thing is accepted.

If all goes well, I will probably go back to standalone app idea too, but not just yet, because I don't want to waste my time on stuff like tabs, sidebar, multi-platform publishing of electron and similar

**Comment by domagojk** [comment]
Btw, dynamodb service has been added.
So if you are using dynamo, you can try it out.
I would grateful for any kind of feedback :)
